### ISSUE TITLE
Getting Not a SFDX command issue

### ISSUE THREAD

**Issue by Varun200864** [nawforce/ApexLink#14] opened 2019-12-15 06:07 UTC
I have installed the plugin.

When trying to run apexlink:check, getting the below issue:

![image](https://user-images.githubusercontent.com/8669506/70858813-256c4d00-1f2f-11ea-88a3-26e87abec3e1.png)

What can be the reason of the above issue?

**Comment by nawforce** [comment] 2019-12-16 18:34
Thanks for reporting this. I think the problem is likely that the sfdx plugins:install has failed without reporting an error. There is some extra complexity mixing node & Java on Windows that I should have put in the README. 

The quick fix for this is to run 'npm install --global windows-build-tools' which will make sure your have all the needed parts. Longer term I am experimenting with have a dual build for node & Java so this kind of problem goes away. I will update the README to point out the issue.

**Comment by nawforce** [comment] 2019-12-17 12:49
README updated

**Closed by nawforce** 2019-12-17 12:49 UTC
